name: Continuous integration

on:
  # Trigger the workflow on push or pull request,
  push:
  # Trigger the workflow via a manual run
  workflow_dispatch:

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install

  unit-test:
    name: Run unit test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [install]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Run tests
        run: python3 -m unittest discover

  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [install]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github .
